#include <stdio.h>

main () {


/*
 DECLARANDO VARIAVEL INTEIRA, A DIVISAO TBM SERA INTEIRA, POR ISSO NAS DIVISOES SAI O RESULTADO
*/


int nota100, nota50,nota10, moeda1, num; //VARIAVEIS

scanf("%d", &num); // ESCANIANDO O VALOR DIGITADO

nota100 = num/100; //DIVIDINDO NUM POR 100 E ACHANDO UM VALOR INTEIRO

num = num%100; // ACHANDO O RESTO DE NUM -- ESSE RESTO IRA SER O NUMERO PARA COMPOR AS NOTAS DE 50
// NOVO VALOR DE NUM = 95

nota50 = num/50; //DIVIDINDO NUM POR 50 E ACHANDO UM VALOR INTEIRO

num = num-(50*nota50); // -- NESSE CASO EU ENCONTREI UM PROBLEMA AO DIVIDIR O NUM POR 50, DAVA 1.9 E NAO IA BATER O RESULTADO, ENTAO ACHEI
                       //  UMA SOLUÇÃO PARA O PROBLEMA, QUE FOI TIRAR A DIFERENÇA DE NUM E A QUANTIDADE DE NOTAS DE 50 ENCONTRADAS NO NOTA50

// NOVO VALOR DE NUM = 45

nota10 = num/10; // DIVINDO POR 10 E ENCONTRANDO QUANTAS NOTAS PRECISAVA

num = num%10; // DIVINDO E ACHANDO O RESTO

// NOVO VALOR DE NUM = 5

moeda1 = num/1; // NESSE CASO NEM PRECISO MAIS FALA NADA, VC ENTENDEU

printf("NOTAS DE 100 = %i\n", nota100);
printf("NOTAS DE 50 = %i\n", nota50);
printf("NOTAS DE 10 = %i\n", nota10);
printf("MOEDAS DE 1 = %i\n", moeda1);
}
