#include <stdio.h>

/*
  DECLARANDO VARIAVEIS INTEIRAS, A DIVISAO SO TERA NUMEROS INTEIROS.
*/

main () {

int n, d3, d2, d1; // DECLARANDO AS VARIAVEIS

scanf("%i",&n); //SCANIANDO O VALOR DOS 3 DIGITOS

d3 = n%10; //DESCOBRINDO O TERCEIRO ALGORISMO, SIMPLESMENTE COM O RESTO | SENDO INTEIRO A DIVISÃO 123/10 O RESTO É 3
n = n/10; // DIVIDI POR 10 PARA ACHAR O RESULTADO DA DIVISÃO QUE É 12, OU SEJA O NOVO VALOR DE N2 = 12 --> 123/10

// O NOVO VALOR DE N2 JA É 12 | DEIXANDO BEM CLARO

d2 = n%10; // DESCOBRINDO O SEGUNDO ALGORISMO, DE NOVO COM O RESTO | SENDO INTEIRO A DIVISAO DE 12/10 | O 12 SAIU DA LINHA 16, DIVIDINDO O RESTO É 2
n = n/10; // DIVIDINDO O 12/10 ENCONTRAREMOS O RESULTADO 1, OU SEJA O NOVO VALOR DE N2 = 1

// O NOVO VALOR DE N2 JA É 1

d1 = n; // COMO SO SOBROU UM DIGITO CLARO Q SERA O PRIMEIRO

printf("%i%i%i\n", d3,d2,d1); // PRINTANDO NA TELA O NOVO NUMERO OU SEJA O NUMERO QUE FOI DIGITITADO  + O CONTROLE

}
